### ISSUE TITLE
Extra menu options not visible in Files menus

### ISSUE THREAD

**Issue by DazeEnd** [nextcloud-libraries/nextcloud-files#933] opened 2024-04-24 19:54 UTC
**Describe the bug**
The LibreSign app adds a new "Open in LibreSign" option to the right-click and ellispis menus in Files, however those menus are not always resized to accommodate this new option.

In the Files app, when the LibreSign app is installed and the details pane is open and width of the browser viewport is relatively narrow, the "Open in LibreSign" option does not appear when you right-click on a file, or when you click the ellipsis ("...") button. It is outside the visible frame of the menu, and you have to scroll to find it. There is no visual indication that the menu can be scrolled, so it is difficult to discover.

**To Reproduce**
1. Log into Nextcloud as an admin and install LibreSign v8.0.0.
2. Open the Files app.
3. Adjust the size of the browser window so that the width of the browser viewport is between 1084 pixels and 1484 pixels.
4. Right-click on a file, and examine the menu that appears.
5. Click on the ellipsis ("...") button next to a file and examine the menu that appears.
6. Right-click on a file, and select "Open Details" to open the details pane.
7. Right-click on a file, and examine the menu that appears.
8. Click on the ellipsis ("...") button next to a file and examine the menu that appears.

**Expected behavior**
In steps 4, 5, 7, and 8, an "Open in LibreSign" option should appear in all the menus that are displayed.

**Actual behavior**
In steps 4 and 5, the "Open in LibreSign" menu option appears as expected.

In steps 7 and 8, the "Open in LibreSign" menu option does not appear unless you scroll down on the menu.

**Screenshots**
Results from Step 4:
![image](https://github.com/nextcloud-libraries/nextcloud-files/assets/2699247/622197a0-d964-42af-8216-7037415a12f8)

Results from Step 5:
![image](https://github.com/nextcloud-libraries/nextcloud-files/assets/2699247/0f87dbf8-e7d1-4904-997f-1ad7e975ba62)

Results from Step 7:
![image](https://github.com/nextcloud-libraries/nextcloud-files/assets/2699247/86e132fa-f101-46dd-8c23-d6e73395367b)

Results from Step 8:
![image](https://github.com/nextcloud-libraries/nextcloud-files/assets/2699247/8b3a89c8-f7b5-4fc6-b5d9-31f1a7123626)

Video showing scrolling the menu:
[Screencast from 2024-04-16 10-22-18.webm](https://github.com/nextcloud-libraries/nextcloud-files/assets/2699247/5cd70d38-ceae-44ae-a315-63afbe8b67ec)

**Environment information:**
- Server OS: AlmaLinux 8.4
- Browser: Firefox
- LibreSign Version: v8.0.0-rc11
- Nextcloud Server Version: 28.0.4
- Logs: N/A

**Additional context:**
This problem seems to be connected to the display of the "Show sharing options" button (![image](https://github.com/nextcloud-libraries/nextcloud-files/assets/2699247/ba9a6fd0-9ad4-4809-aeed-c280c1df8fdd)) on a file's row. When the "Show sharing options" button is displayed, then the problem does not appear for me. When the width of the browser window is adjusted so that the "Show sharing options" button disappears (and the option is moved to the menu), then the problem appears.

**Comment by DazeEnd** [comment] 2024-04-24 19:55
Also, if this isn't the right place to file this issue, please let me know where the proper place would be. Thanks.

**Comment by susnux** [comment] 2024-04-29 23:11
Duplicate of https://github.com/nextcloud-libraries/nextcloud-vue/issues/3920

In newer versions the scrolling will be at least more obvious :)

**Closed by susnux** 2024-04-29 23:11 UTC
